behaviors:
  poki_Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2000
      buffer_size: 32000

      learning_rate: 0.0003

      beta: 0.007
      epsilon: 0.2
      lambd: 0.925

      num_epoch: 6
      learning_rate_schedule: linear

    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 516
    summary_freq: 50000
    threaded: true

    network_settings:
#      normalize: true
      hidden_units: 9
      num_layers: 2
      vis_encode_type: simple

    reward_signals:

      curiosity:
        strength: 0.25
        gamma: 0.9
        encoding_size: 128

      extrinsic:
        gamma: 0.995
        strength: 1.0

#      gail:
#        demo_path: C:\Users\Cody\Documents\Unity\rotkr\Assets\ML-Agents\Demonstrations\it0small.demo
#        strength: 0.0 
#        #0.005
#        gamma: 0.85
#        encoding_size: 128

#    behavioral_cloning:
#        demo_path: C:\Users\Cody\Documents\Unity\rotkr\Assets\ML-Agents\Demonstrations\it0small.demo
#        strength: 0.0
#        #0.005

    