behaviors:
  poki_Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 8
      vis_encode_type: simple

    reward_signals:
 #     curiosity:
 #       strength: 0.1
 #       gamma: 0.995

      extrinsic:
        gamma: 0.99
        strength: 1.0

#      gail:
#        demo_path: C:\Users\Cody\Documents\Unity\rotkr\Assets\ML-Agents\Demonstrations\BasicDemo.demo
#        strength: 0.05
#        gamma: 0.99

    behavioral_cloning:
        demo_path: C:\Users\Cody\Documents\Unity\rotkr\Assets\ML-Agents\Demonstrations\BasicDemo.demo
        strength: 0.60
        steps: 3000000

    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 50000
    threaded: true